Repository pingcap-inc/tidb.io, pull requests merged in 2022-03, with the labels that each got.

#377 CP 308: member center fix
  .env.development
  packages/common/src/utils/form/index.spec.js
  public/images/profile/undraw_ride_a_bicycle_re_6tjy.svg
  src/pages/member/index.page.tsx
  src/pages/member/index.styled.ts
  src/pages/member/layout/Layout.component.js
  src/pages/member/layout/index.js
  src/pages/member/layout/layout.styled.js
  src/pages/member/layout/menu/Menu.component.js
  src/pages/member/layout/menu/index.js
  src/pages/member/layout/menu/menu.styled.js
  src/pages/member/records/index.page.tsx
  src/pages/member/records/index.styled.ts
  src/pages/member/redeem/form/Form.component.tsx
  src/pages/member/redeem/form/form.fields.js
  src/pages/member/redeem/form/form.styled.js
  src/pages/member/redeem/form/index.js
  src/pages/member/redeem/index.page.tsx
  src/pages/member/redeem/index.styled.ts
  src/pages/member/redeem/records/index.page.tsx
  src/pages/member/redeem/records/index.styled.ts
  src/pages/member/rules/index.page.js
  src/pages/member/rules/index.styled.ts
  src/pages/u/[username]/constant.data.ts
  src/pages/u/[username]/username.ts
  src/pages/vip-center/rules/index.page.js
Labels: P1

#379 Fix events page
  packages/i18n/locales/zh/page-events.json
Labels: P2

#383 fix: production deploy
  next.config.js
  packages/datasource/src/api/initStrapiClient.js
  src/components/errorPage/ErrorPage.component.js
  src/pages/blog/[[...slugs]].page.js
  src/pages/blog/[slug]/index.page.js
  src/pages/blog/audits/index.page.js
  src/pages/blog/tag/index.page.js
  src/pages/blog/user/[id]/posts/[[...type]].page.js
  src/pages/home/activities/Activities.component.js
  src/utils/common.utils.js
Labels: P0

#387 Optimize events index page (support SSR, migrate to TypeScript)
  package-lock.json
  package.json
  packages/common/package.json
  packages/datasource/package-lock.json
  packages/datasource/package.json
  packages/datasource/src/api/blog/common.ts
  packages/datasource/src/api/cms/index.ts
  packages/datasource/src/api/index.d.ts
  packages/datasource/src/api/index.js
  packages/i18n/package-lock.json
  packages/ui/package-lock.json
  src/layouts/core/Core.component.js
  src/layouts/twoColumnsSection/TwoColumnsSection.component.tsx
  src/layouts/twoColumnsSection/index.ts
  src/layouts/twoColumnsSection/twoColumnsSection.styled.ts
  src/pages/events/cooperation/Cooperation.component.js
  src/pages/events/events.slice.js
  src/pages/events/index.page.js
  src/pages/events/index.page.tsx
  src/pages/events/index/about/About.component.tsx
  src/pages/events/index/about/about.styled.ts
  src/pages/events/index/about/index.ts
  src/pages/events/index/constant.json
  src/pages/events/index/cooperation/Cooperation.component.tsx
  src/pages/events/index/cooperation/cooperation.styled.ts
  src/pages/events/index/cooperation/index.ts
  src/pages/events/index/cooperation/logo.svg
  src/pages/events/index/list/List.component.tsx
  src/pages/events/index/list/index.ts
  src/pages/events/index/list/list.constants.ts
  src/pages/events/index/list/list.styled.ts
  src/pages/events/list/List.component.js
  src/redux/index.js
  src/utils/request.utils.ts
Labels: enhancement

#389 refactor: use anchor instead of next/link
  packages/datasource/src/api/cms/index.ts
  packages/i18n/locales/zh/page-home.json
  src/components/Anchor.tsx
  src/pages/home/activities/Activities.component.js
  src/pages/home/activities/activity/Activity.component.js
  src/pages/home/activities/activity/activity.styled.js
  src/pages/home/activities/meetup/Meetup.component.js
  src/pages/home/banner/Banner.component.js
  src/pages/home/banner/banner.styled.js
  src/pages/home/contribution/Contribution.component.js
  src/pages/home/contribution/contribution.styled.js
  src/pages/home/forum/Forum.component.js
  src/pages/home/forum/forum.styled.js
  src/pages/home/forum/post/Post.component.js
  src/pages/home/index.js
  src/pages/home/learning/Learning.component.js
  src/pages/home/learning/learning.styled.js
  src/pages/home/others/Others.component.js
  src/pages/home/others/others.styled.js
  src/pages/home/others/videoThumbnail/VideoThumbnail.component.js
  src/pages/home/others/videoThumbnail/videoThumbnail.style.js
  src/pages/home/subscription/Subscription.component.js
  src/pages/home/subscription/subscription.styled.js
  src/pages/home/welcome/Welcome.component.js
Labels: enhancement, P1

#394 fix blog style: increase the top size for match the header height
  src/pages/blog/_components/BlogHomepage/index.styled.js
Labels: bug, P1

#393 fix: new deployment bugs
  package-lock.json
  package.json
  src/api/asktug/index.ts
  src/pages/blog/[slug]/components/AuthorInfo/AuthorInfo.component.js
  src/pages/blog/[slug]/components/Comments/Comments.component.js
  src/pages/blog/[slug]/components/Interactions/interactions.hooks.js
  src/pages/blog/[slug]/index.page.js
  src/pages/blog/_components/BlogInfo/BlogInfo.component.js
  src/pages/blog/_components/BlogList/BlogList.component.js
  src/pages/blog/_components/CategoryList/CategoryList.component.js
  src/pages/blog/_components/PostItem/index.styled.ts
  src/pages/blog/_components/PostItem/index.tsx
  src/pages/blog/audits/AuditList.js
  src/pages/blog/user/Tab.js
  src/pages/blog/user/Tab.styled.js
  src/pages/blog/user/[id]/Layout.component.js
  src/pages/blog/user/[id]/comments.page.js
  src/pages/blog/user/[id]/favorites.page.js
  src/pages/blog/user/[id]/index.page.tsx
  src/pages/blog/user/[id]/index.styled.js
  src/pages/blog/user/[id]/like.page.js
  src/pages/blog/user/[id]/posts/StatusSelect.component.tsx
  src/pages/blog/user/[id]/posts/[[...type]].page.js
  src/pages/blog/user/_component/CommentPostItem/index.styled.ts
  src/pages/blog/user/_component/CommentPostItem/index.tsx
  src/pages/home/blogs/api.ts
  src/pages/notifications/index.page.tsx
  src/pages/private-messages/index.page.tsx
  src/pages/private-messages/sent.page.tsx
  src/pages/u/[username]/_components/ProfileCard/index.tsx
  src/pages/u/[username]/post/[[...status]].page.tsx
  src/pages/u/[username]/post/post-info.ts
  testurls.mjs
Labels: P0
